function Connect-MDA {
[CmdletBinding()] param(
  [string[]]$GraphScopes=@('User.Read.All','Group.Read.All','Directory.Read.All','Policy.Read.All','Application.Read.All','Sites.Read.All','Mail.Send','DeviceManagementApps.Read.All','DeviceManagementConfiguration.Read.All','DeviceManagementManagedDevices.Read.All','DeviceManagementRBAC.Read.All'),
  [switch]$ConnectPnP,[string]$TenantAdminUrl,[switch]$ConnectTeams,[switch]$ConnectEXO,[string]$EXOUserPrincipalName,[string]$TenantId,[string]$TenantDomain,[string]$ProfilePath)
  if ($ProfilePath){ try { Write-Log -Message ("Loading profile: "+$ProfilePath) -Level INFO; $profileJson = Get-Content -Path $ProfilePath -Raw | ConvertFrom-Json; if (-not $TenantId -and $profileJson.TenantId){ $TenantId = $profileJson.TenantId }; if (-not $TenantDomain -and $profileJson.TenantDomain){ $TenantDomain = $profileJson.TenantDomain }; if (-not $TenantAdminUrl -and $profileJson.TenantAdminUrl){ $TenantAdminUrl = $profileJson.TenantAdminUrl }; if (-not $EXOUserPrincipalName -and $profileJson.EXOUserPrincipalName){ $EXOUserPrincipalName = $profileJson.EXOUserPrincipalName }; if ($profileJson.GraphScopes){ $GraphScopes = @($profileJson.GraphScopes) }; if ($profileJson.ConnectPnP){ $ConnectPnP = [bool]$profileJson.ConnectPnP }; if ($profileJson.ConnectTeams){ $ConnectTeams = [bool]$profileJson.ConnectTeams }; if ($profileJson.ConnectEXO){ $ConnectEXO = [bool]$profileJson.ConnectEXO }; Write-Log -Message 'Profile loaded.' -Level INFO } catch { Write-Log -Message ("Profile load failed: " + $_.Exception.Message) -Level WARN } }
  # Decrypt encrypted fields if present
  foreach($fld in 'TenantId','TenantDomain','TenantAdminUrl','EXOUserPrincipalName'){ $val = (Get-Variable -Name $fld -Scope 1 -ErrorAction SilentlyContinue).Value; if ($val -is [psobject] -and $val.PSObject.Properties.Name -contains 'value'){ try { $plain = Unprotect-String -Encrypted $val; Set-Variable -Name $fld -Value $plain -Scope 1; Write-Log -Message ("Decrypted profile field: "+$fld) -Level DEBUG } catch {} } }
  if ($TenantId){ $Script:MDA_TenantId = $TenantId }; if ($TenantDomain){ $Script:MDA_TenantDomain = $TenantDomain }
  # Graph
  try { $graphParams = @{ Scopes=$GraphScopes; NoWelcome=$true }; if ($TenantId){ $graphParams.TenantId = $TenantId }; Write-Log -Message ('Connecting to Microsoft Graph' + ($(if($TenantId){" (TenantId="+$TenantId+")"}))) -Level INFO; Connect-MgGraph @graphParams | Out-Null; $ctx = Get-MgContext; Write-Log -Message ("Connected to Graph. TenantId="+$ctx.TenantId) -Level INFO } catch { Write-Log -Message ("Graph connection failed: " + $_.Exception.Message) -Level ERROR; throw }
  # PnP
  if ($ConnectPnP){ if (-not $TenantAdminUrl){ throw 'TenantAdminUrl is required when -ConnectPnP is specified' }; try { Connect-PnPOnline -Url $TenantAdminUrl -Interactive; Write-Log -Message 'Connected to SharePoint Admin (PnP).' -Level INFO } catch { Write-Log -Message ("PnP connection failed: "+$_.Exception.Message) -Level ERROR } }
  # Teams
  if ($ConnectTeams){ try { $t=@{}; if ($TenantId){ $t.TenantId=$TenantId }; Connect-MicrosoftTeams @t | Out-Null; Write-Log -Message 'Connected to Microsoft Teams.' -Level INFO } catch { Write-Log -Message ("Teams connection failed: "+$_.Exception.Message) -Level WARN } }
  # EXO
  if ($ConnectEXO){ try { if ($EXOUserPrincipalName -and $TenantDomain){ Connect-ExchangeOnline -UserPrincipalName $EXOUserPrincipalName -Organization $TenantDomain -ShowBanner:$false | Out-Null } elseif ($EXOUserPrincipalName){ Connect-ExchangeOnline -UserPrincipalName $EXOUserPrincipalName -ShowBanner:$false | Out-Null } elseif ($TenantDomain){ Connect-ExchangeOnline -Organization $TenantDomain -ShowBanner:$false | Out-Null } else { Connect-ExchangeOnline -ShowBanner:$false | Out-Null }; Write-Log -Message 'Connected to Exchange Online.' -Level INFO } catch { Write-Log -Message ("Exchange Online connection failed: "+$_.Exception.Message) -Level ERROR } }
}
