function Export-ConditionalAccessDeepDive { [CmdletBinding()] param([string]$ReportPath)
  Write-Log -Message 'Exporting Conditional Access deep dive...' -Level INFO
  $policies = Get-MgIdentityConditionalAccessPolicy -All; $locations = Get-MgIdentityConditionalAccessNamedLocation -All; $locMap=@{}; foreach($l in $locations){ $locMap[$l.Id]=$l.DisplayName }
  $rows = foreach($p in $policies){ $u=$p.Conditions.Users; $a=$p.Conditions.Applications; $pl=$p.Conditions.Platforms; $ds=$p.Conditions.DeviceStates; $ga=$p.GrantControls; $sc=$p.SessionControls; [pscustomobject]@{ Id=$p.Id; DisplayName=$p.DisplayName; State=$p.State; ReportOnly=($p.State -eq 'reportOnly'); IncludeUsers=($u.IncludeUsers -join ';'); ExcludeUsers=($u.ExcludeUsers -join ';'); IncludeGroups=($u.IncludeGroups -join ';'); ExcludeGroups=($u.ExcludeGroups -join ';'); IncludeApplications=($a.IncludeApplications -join ';'); ExcludeApplications=($a.ExcludeApplications -join ';'); ClientApps=($p.Conditions.ClientAppTypes -join ';'); PlatformsInclude=($pl.IncludePlatforms -join ';'); PlatformsExclude=($pl.ExcludePlatforms -join ';'); DeviceStatesInclude=($ds.IncludeStates -join ';'); DeviceStatesExclude=($ds.ExcludeStates -join ';'); LocationsInclude=(($p.Conditions.Locations.IncludeLocations | ForEach-Object { if ($locMap.ContainsKey($_)){$locMap[$_]}else{$_} }) -join ';'); LocationsExclude=(($p.Conditions.Locations.ExcludeLocations | ForEach-Object { if ($locMap.ContainsKey($_)){$locMap[$_]}else{$_} }) -join ';'); GrantBuiltIn=($ga.BuiltInControls -join ';'); GrantOperator=$ga.Operator; SessionJson=([string]($sc | ConvertTo-Json -Depth 4)); HasExclusions=[bool](($u.ExcludeUsers.Count+$u.ExcludeGroups.Count+$u.ExcludeRoles.Count) -gt 0 -or $p.Conditions.Locations.ExcludeLocations.Count -gt 0) } }
  $kpi = [pscustomobject]@{ EnabledPolicies=($rows | Where-Object { $_.State -eq 'enabled' }).Count; ReportOnlyPolicies=($rows | Where-Object { $_.ReportOnly }).Count; DisabledPolicies=($rows | Where-Object { $_.State -eq 'disabled' }).Count; PoliciesWithExclusions=($rows | Where-Object { $_.HasExclusions }).Count }
  $int = Write-IntermediateJson -Name 'conditional-access-deep' -Data @{ Policies=$rows; KPIs=$kpi } -ReportPath $ReportPath
  $paths = Out-ReportFiles -BaseName 'conditional-access-deep' -Data $rows -ReportPath $ReportPath -Title 'Conditional Access (Deep Dive)' -Intro 'Fine-grained CA report.'
  [pscustomobject]@{ Data=@{Policies=$rows;KPIs=$kpi}; Intermediate=$int; Paths=$paths }
}
