function Export-EXOMailboxes { [CmdletBinding()] param([string]$ReportPath,[switch]$IncludeStatistics,[int]$ThrottleMs=0)
  Write-Log -Message 'Exporting EXO mailboxes...' -Level INFO
  $props = @('DisplayName','PrimarySmtpAddress','UserPrincipalName','RecipientTypeDetails','WhenCreated','LitigationHoldEnabled','RetentionHoldEnabled','AuditEnabled','ArchiveStatus','HiddenFromAddressListsEnabled','ForwardingSmtpAddress','DeliverToMailboxAndForward','MailboxPlan','RoleAssignmentPolicy','MessageCopyForSentAsEnabled','MessageCopyForSendOnBehalfEnabled','EmailAddresses')
  try { $mbxs = Get-EXOMailbox -ResultSize Unlimited -Properties $props } catch { $mbxs=@(); Write-Log -Level ERROR -Message $_.Exception.Message }
  $rows=@(); foreach($m in $mbxs){ $row=[pscustomobject]@{ DisplayName=$m.DisplayName; PrimarySmtpAddress=$m.PrimarySmtpAddress; UserPrincipalName=$m.UserPrincipalName; Type=$m.RecipientTypeDetails; Created=$m.WhenCreated; LitigationHoldEnabled=$m.LitigationHoldEnabled; RetentionHoldEnabled=$m.RetentionHoldEnabled; AuditEnabled=$m.AuditEnabled; ArchiveStatus=$m.ArchiveStatus; HiddenFromAL=$m.HiddenFromAddressListsEnabled; ForwardingSmtpAddress=$m.ForwardingSmtpAddress; DeliverToMailboxAndForward=$m.DeliverToMailboxAndForward; MailboxPlan=$m.MailboxPlan; RoleAssignmentPolicy=$m.RoleAssignmentPolicy; SentAsCopy=$m.MessageCopyForSentAsEnabled; SendOnBehalfCopy=$m.MessageCopyForSendOnBehalfEnabled; EmailAddressCount=($m.EmailAddresses | Where-Object { $_ -like 'SMTP:*' -or $_ -like 'smtp:*' }).Count; ItemCount=$null; TotalItemSize=$null; LastLogonTime=$null }; if ($IncludeStatistics){ try { $s = Get-EXOMailboxStatistics -Identity $m.PrimarySmtpAddress; if ($s){ $row.ItemCount=$s.ItemCount; $row.TotalItemSize=$s.TotalItemSize; $row.LastLogonTime=$s.LastLogonTime } } catch { Write-Log -Level WARN -Message $_.Exception.Message }; if ($ThrottleMs -gt 0){ Start-Sleep -Milliseconds $ThrottleMs } }; $rows += $row }
  $int = Write-IntermediateJson -Name 'exo-mailboxes' -Data $rows -ReportPath $ReportPath
  $paths = Out-ReportFiles -BaseName 'exo-mailboxes' -Data $rows -ReportPath $ReportPath -Title 'EXO: Mailboxes' -Intro 'Mailbox posture.'
  [pscustomobject]@{ Data=$rows; Intermediate=$int; Paths=$paths }
}
