function Send-ReportEmail {
[CmdletBinding()] param([Parameter(Mandatory)][string]$To,[Parameter(Mandatory)][string]$Subject,[string]$From,[Parameter()][string[]]$AttachmentPaths,[string]$SmtpServer,[int]$SmtpPort=25,[pscredential]$SmtpCredential,[switch]$UseGraph,[string]$GraphUserId)
  Write-Log -Message 'Sending report email...' -Level INFO
  $paths = Get-ReportPaths -BaseName 'overview'; $overviewHtml = Get-Content -Path $paths.Html -Raw -ErrorAction SilentlyContinue
  $brandCss = Get-MDABrandCss; $logoTag = Get-MDABrandLogoTag
  $bodyHtml = "<html><head><meta charset='utf-8'><style>$brandCss</style><link href='https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600&display=swap' rel='stylesheet'></head><body><div class='header'>$logoTag<div class='title'>$Subject</div></div><hr class='brand'/><div class='card'><h2 style='margin-top:0;color:var(--mdl-secondary)'>Summary</h2><div style='font-size:13px;color:#333'>See attached HTML reports for full details.</div></div>" + $overviewHtml + "</body></html>"
  if ($UseGraph){ if (-not $GraphUserId){ $GraphUserId='me' }; $attachments=@(); foreach($p in $AttachmentPaths){ if (Test-Path $p){ $bytes=[IO.File]::ReadAllBytes($p); $b64=[Convert]::ToBase64String($bytes); $attachments += @{ '@odata.type'='#microsoft.graph.fileAttachment'; Name=(Split-Path $p -Leaf); ContentBytes=$b64 } } }; $message = @{ subject=$Subject; body=@{ contentType='HTML'; content=$bodyHtml }; toRecipients=@(@{emailAddress=@{address=$To}}); attachments=$attachments }; Send-MgUserMail -UserId $GraphUserId -Message $message -SaveToSentItems | Out-Null; Write-Log -Message 'Email sent via Graph.' -Level INFO }
  else { if (-not $From){ throw 'From is required when using SMTP' }; $mail=@{ To=$To; From=$From; Subject=$Subject; Body=$bodyHtml; BodyAsHtml=$true; SmtpServer=$SmtpServer; Port=$SmtpPort }; if ($SmtpCredential){ $mail.Credential=$SmtpCredential; $mail.UseSsl=$true }; if ($AttachmentPaths){ $mail.Attachments=$AttachmentPaths }; Send-MailMessage @mail; Write-Log -Message 'Email sent via SMTP.' -Level INFO }
}
