function New-HtmlReport {
  [CmdletBinding()] param([Parameter(Mandatory)][string]$Title,[Parameter(Mandatory)][ValidateNotNull()]$Data,[string]$Subtitle)
  $brandCss = Get-MDABrandCss; $logoTag = Get-MDABrandLogoTag; $meta = "Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz') | Host: $env:COMPUTERNAME"
  $tableHtml = ConvertTo-TableHtml -Data $Data
  @"<html><head><meta charset='utf-8'><title>$Title</title><style>$brandCss</style><link href='https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600&display=swap' rel='stylesheet'></head><body><div class='header'>$logoTag<div class='title'>$Title</div></div><hr class='brand'/><div class='card'><h2 style='color:var(--mdl-secondary);margin-top:0;'>$Subtitle</h2><div class='meta' style='color:#666;font-size:12px;margin-bottom:16px'>$meta</div><div class='content'>$tableHtml</div></div><footer>Generated by M365.DocumentAssistant</footer></body></html>"@
}
